### PR TITLE
Implement OB error class in taxonomy_units

### PR DESCRIPTION
**Pull request by cwhanse**
Also, some edits to method logic for clarity

### CODE REVIEW

**Comment by cwhanse** [comment]
I'm not sure I follow.  If `unit_str` isn't a valid `unit_id`, 'unit_name` or `id` then `get_unit` will raise the error and terminate.  I don't think it will ever pass `None` back as the unit.  Are you saying that you'd prefer that `get_unit` pass back `None` and an error message, rather than raising the error?

**Comment by cwhanse** [comment]
An alternative logic for `cli.py`:
```
def list_unit_details(args):
    try:
        unit = taxonomy.units.get_unit(args.unit)
         print...
    except OBNotFoundError:
          print("Not found")
```

**Comment by joelebwf** [comment]
The alternative logic looks fine to me.  Feel free to implement and merge.

I originally programmed the get_ statements to pas None for "Not Found".  That is not necessarily best - just the way I did things.  I think we should just keep the discussion going on how to return errors.

**Comment by cwhanse** [comment]
OK.  The other calls to `get_unit` in `cli.list_units_details` are OK, since they are within a loop over a list of taxonomy units, rather than some other input.

**Pull request merged**
