### PR TITLE
clean up validation in taxonomy_semantic

### PR DESCRIPTION
**Pull request by cwhanse**
Change `validate_concept` to `is_concept`.  Use `is_concept` in `validate_concept_value`.  `validate_concept_value` already references `validator`.

### CODE REVIEW

**Comment by jessiedeot** [comment]
@cla-bot check

**Comment by joelebwf** [comment]
Note that the decision to have Taxonomy call validator via "validate_concept_value" was extremely early (before data_model.py or validator.py existed) in development and we can keep the check there or refactor, either works for me.  The CLI currently calls the method in TaxonomySemantic.  As far as naming conventions I think we need to prioritize the API signature review (which basically has all of us agreeing to use the same convention throughout the system) so we are all on the same page and consistent throughout.

**Comment by joelebwf** [comment]
We definitely agreed to move the bulk of the logic to Validator - we also discussed whether Validator should be called by Parser or by DataModel.   I actually forgot that Taxonomy had a call in it to Validator and there is only one mandatory operation that has to be in Taxonomy (validate that the concept itself is valid and return its meta-data so that Validator can operate).  It may not matter if Taxonomy is called first and then calls Validator or if Validator is called first and then queries Taxonomy - someone will need to study the code to figure out if one of these orders is more efficient.  The only design principle that needs to be avoided is circular dependency (don't call Taxonomy -> Validator -> Taxonomy) so if you feel that a particular call order better avoids this I would go ahead and implement.

Your pull is failing because there needs to be a change in cli.py:

raceback (most recent call last):
  File "scripts/cli/cli.py", line 468, in <module>
    globals()[args.command](args)
  File "scripts/cli/cli.py", line 252, in validate_concept
    print("Valid:", tax.semantic.validate_concept(args.concept))
AttributeError: 'TaxonomySemantic' object has no attribute 'validate_concept'

If you just want to change it to get it to work right now that is fine with me.  I'll try to draw up some sample call sequences so we have something to look at.

**Comment by joelebwf** [comment]
Is this handled in another pull request or does it still need review?  I think we can just close this one because it was taken care of elsewhere but I could be wrong.

**Comment by cwhanse** [comment]
This PR is no longer needed.

**Pull request closed without merging**
